<a href="https://colab.research.google.com/github/12mdkawsar/HearDiseaseDateset23.09.26/blob/main/HearDiseaseDateset23_09_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#part 1 import  libraries
#step 1
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#Load dataset link
df = pd.read_csv("/content/heart-selected-columns.csv")

In [ ]:
df

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak
0      52    1   0       125   212    0        1      168      0      1.0
1      53    1   0       140   203    1        0      155      1      3.1
2      70    1   0       145   174    0        1      125      1      2.6
3      61    1   0       148   203    0        1      161      0      0.0
4      62    0   0       138   294    1        1      106      0      1.9
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
1020   59    1   1       140   221    0        1      164      1      0.0
1021   60    1   0       125   258    0        0      141      1      2.8
1022   47    1   0       110   275    0        0      118      1      1.0
1023   50    0   0       110   254    0        0      159      0      0.0
1024   54    1   0       120   188    0        1      113      0      1.4

[1025 rows x 10 columns]

In [ ]:
#Analytical view
#step 3
df.shape

(1025, 10)

In [ ]:
#Total Feature &sample
print(f"total feature : {df.shape[1]}")
print(f"total samples: {df.shape[0]}")

total feature : 10
total samples: 1025

In [ ]:
#kesu row and kesu data dekhar dorkhar
# step 4 view dataset
df.head(10)

   age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak
0   52    1   0       125   212    0        1      168      0      1.0
1   53    1   0       140   203    1        0      155      1      3.1
2   70    1   0       145   174    0        1      125      1      2.6
3   61    1   0       148   203    0        1      161      0      0.0
4   62    0   0       138   294    1        1      106      0      1.9
5   58    0   0       100   248    0        0      122      0      1.0
6   58    1   0       114   318    0        2      140      0      4.4
7   55    1   0       160   289    0        0      145      1      0.8
8   46    1   0       120   249    0        0      144      0      0.8
9   54    1   0       122   286    0        0      116      1      3.2

In [ ]:
#sample 10
df.sample(10)

      age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak
1000   64    1   0       145   212    0        0      132      0      2.0
261    54    1   2       150   232    0        0      165      0      1.6
72     56    1   0       125   249    1        0      144      1      1.2
477    57    1   2       128   229    0        0      150      0      0.4
168    43    1   2       130   315    0        1      162      0      1.9
448    51    0   2       120   295    0        0      157      0      0.6
264    58    0   0       170   225    1        0      146      1      2.8
634    52    1   0       125   212    0        1      168      0      1.0
654    41    0   1       126   306    0        1      163      0      0.0
83     38    1   2       138   175    0        1      173      0      0.0

In [ ]:
#category velue and numerical value
cat_cols= df.select_dtypes(include=["object"]).columns
num_cols= df.select_dtypes(exclude=["object"]).columns
print(f'categorical columns:{cat_cols}')
print(f'numerical columns:{num_cols}')

categorical columns:Index([], dtype='object')
numerical columns:Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak'],
      dtype='object')

In [ ]:
#part 2 Feature screening & cleaning